name: Build Elementic Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clean install
        run: npm ci

      - name: Build + Deploy
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # - name: Deploy
        #   uses: peaceiris/actions-gh-pages@v3
        #   with:
        #     publish_dir: ./_site
        #     github_token: ${{ secrets.GITHUB_TOKEN }}
