- name: Build Elementic Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clean install
        run: npm ci

      - name: Build + Deploy
        run: npm run deploy

        # - name: Deploy
        #   uses: peaceiris/actions-gh-pages@v3
        #   with:
        #     publish_dir: ./_site
        #     github_token: ${{ secrets.GITHUB_TOKEN }}
