name: Build Elementic Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies & build production
        run: |
          npm ci
          npm run build:prod

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     publish_dir: ./_site
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
